/*PRE WORK*/
create table CUSTOMER(
CUSTOMER_ID VARCHAR(50) CONSTRAINT customerid  PRIMARY KEY,
FIRSTNAME VARCHAR(20),
MIDDLENAMEINITIAL CHAR(1),
LASTNAME VARCHAR(30),
BIRTHDATE DATE CONSTRAINT DOB NOT NULL,
AGE DECIMAL
)

CREATE SEQUENCE CUSTOMERID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO CUSTOMER VALUES (CUSTOMERID_SEQUENCE.NEXTVAL,'BHAI','A','SAB','07-JAN-2018',22);
INSERT INTO CUSTOMER VALUES (CUSTOMERID_SEQUENCE.NEXTVAL,'BHAI','A','JAAN','17-JAN-2017',42);
INSERT INTO CUSTOMER VALUES (CUSTOMERID_SEQUENCE.NEXTVAL,'JAY','A','SRI','07-MAR-2015',72);
INSERT INTO CUSTOMER VALUES (CUSTOMERID_SEQUENCE.NEXTVAL,'BHAI','A','SAB','07-FEB-2018',82);
INSERT INTO CUSTOMER VALUES(CUSTOMERID_SEQUENCE.NEXTVAL,'JAY','B','SRI','07-JAN-2018',92);
INSERT INTO CUSTOMER VALUES (CUSTOMERID_SEQUENCE.NEXTVAL,'Khatta','B','MITTA','07-DEC-2013',32);

/*===========================================================================================================*/


/* Distinct or Unique clause - Select distinct values from a FIRSTNAME column. */
SELECT DISTINCT FIRSTNAME FROM CUSTOMER


/* Distinct or Unique clause with multiple columns  */
Select distinct values within FIRSTNAME AND LASTNAME columns

/*SELECT DISTINCT FIRSTNAME,LASTNAME FROM CUSTOMER*/


/*Specify same column name in select statement multiple time and make use of functions  - UPPER()*/
SELECT LOWER(FIRSTNAME),FIRSTNAME FROM CUSTOMER

/*Clauses: ORDER BY, GROUP BY, HAVING. 
GROUP BY and HAVING clause are used in conjunction. It is often used with aggregate function  (COUNT, MAX, MIN, SUM, AVG)*/

SELECT * FROM CUSTOMER ORDER BY BIRTHDATE
SELECT COUNT(CUSTOMER_ID),FIRSTNAME FROM CUSTOMER GROUP BY FIRSTNAME;
SELECT COUNT(CUSTOMER_ID),FIRSTNAME FROM CUSTOMER GROUP BY FIRSTNAME HAVING  FIRSTNAME='BHAI';

/* SELECT WITH EXPRESSIONS*/
SELECT AGE*2 FROM CUSTOMER WHERE 22=AGE

/*Below query is valid and ill return all the rows in the table as WHERE expression evaluates to true;*/
SELECT AGE*2 FROM CUSTOMER WHERE 22=22

/* ROWNUM and ROWID 
This are Pseudocolumns maintained by oracle db system for every Table.*/

SELECT AGE,ROWNUM,ROWID  FROM CUSTOMER

/* CREATING INDEX */

CREATE INDEX CUST_FIRSTNAME_INDX ON CUSTOMER (FIRSTNAME)
